name: Deploy Node Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u "${{secrets.DOCKER_USERNAME}}" --password-stdin
      - name: Build Docker Image
        run: docker build -t ahtashammustafa/realestate-app .
      - name: Publish Image to docker hub
        run: docker push ahtashammustafa/realestate-app:latest

  deploy:  
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Image from docker hub
        run: docker pull ahtashammustafa/realestate-app:latest
      - name: Run Docker Container
        run: docker run -d -p 8000:8000 --name realestate-app-container -e DATABASE_URL="mongodb+srv://ahtshammustufa786:rgpEhkXQZaSCz9M1@realestate.97jy373.mongodb.net/realestate?retryWrites=true&w=majority&appName=RealEstate" -e JWT_SECRET_KEY="shami" ahtashammustafa/realestate-app